// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(needsAuth)/_middleware.tsx";
import * as $1 from "./routes/(needsAuth)/api/score/index.tsx";
import * as $2 from "./routes/(needsAuth)/play.tsx";
import * as $3 from "./routes/(needsAuth)/ws.tsx";
import * as $4 from "./routes/_404.tsx";
import * as $5 from "./routes/_app.tsx";
import * as $6 from "./routes/_middleware.tsx";
import * as $7 from "./routes/devotrio.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/leaderboard.tsx";
import * as $10 from "./routes/rules.tsx";
import * as $11 from "./routes/user/login.tsx";
import * as $12 from "./routes/user/logout.tsx";
import * as $$0 from "./islands/Joke.tsx";
import * as $$1 from "./islands/Log.tsx";
import * as $$2 from "./islands/Login.tsx";
import * as $$3 from "./islands/Otrio.tsx";
import * as $$4 from "./islands/Settings.tsx";
import * as $$5 from "./islands/_OtrioOld.tsx";

const manifest = {
  routes: {
    "./routes/(needsAuth)/_middleware.tsx": $0,
    "./routes/(needsAuth)/api/score/index.tsx": $1,
    "./routes/(needsAuth)/play.tsx": $2,
    "./routes/(needsAuth)/ws.tsx": $3,
    "./routes/_404.tsx": $4,
    "./routes/_app.tsx": $5,
    "./routes/_middleware.tsx": $6,
    "./routes/devotrio.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/leaderboard.tsx": $9,
    "./routes/rules.tsx": $10,
    "./routes/user/login.tsx": $11,
    "./routes/user/logout.tsx": $12,
  },
  islands: {
    "./islands/Joke.tsx": $$0,
    "./islands/Log.tsx": $$1,
    "./islands/Login.tsx": $$2,
    "./islands/Otrio.tsx": $$3,
    "./islands/Settings.tsx": $$4,
    "./islands/_OtrioOld.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
