// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_needsAuth_middleware from "./routes/(needsAuth)/_middleware.tsx";
import * as $_needsAuth_api_score_index from "./routes/(needsAuth)/api/score/index.tsx";
import * as $_needsAuth_play from "./routes/(needsAuth)/play.tsx";
import * as $_needsAuth_ws from "./routes/(needsAuth)/ws.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $index from "./routes/index.tsx";
import * as $leaderboard from "./routes/leaderboard.tsx";
import * as $rules from "./routes/rules.tsx";
import * as $user_login from "./routes/user/login.tsx";
import * as $user_logout from "./routes/user/logout.tsx";
import * as $CicleSet from "./islands/CicleSet.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Joke from "./islands/Joke.tsx";
import * as $Log from "./islands/Log.tsx";
import * as $Logger from "./islands/Logger.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $Otrio from "./islands/Otrio.tsx";
import * as $Settings from "./islands/Settings.tsx";
import * as $Slot from "./islands/Slot.tsx";
import * as $_OtrioOld from "./islands/_OtrioOld.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(needsAuth)/_middleware.tsx": $_needsAuth_middleware,
    "./routes/(needsAuth)/api/score/index.tsx": $_needsAuth_api_score_index,
    "./routes/(needsAuth)/play.tsx": $_needsAuth_play,
    "./routes/(needsAuth)/ws.tsx": $_needsAuth_ws,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/index.tsx": $index,
    "./routes/leaderboard.tsx": $leaderboard,
    "./routes/rules.tsx": $rules,
    "./routes/user/login.tsx": $user_login,
    "./routes/user/logout.tsx": $user_logout,
  },
  islands: {
    "./islands/CicleSet.tsx": $CicleSet,
    "./islands/Counter.tsx": $Counter,
    "./islands/Joke.tsx": $Joke,
    "./islands/Log.tsx": $Log,
    "./islands/Logger.tsx": $Logger,
    "./islands/Login.tsx": $Login,
    "./islands/Otrio.tsx": $Otrio,
    "./islands/Settings.tsx": $Settings,
    "./islands/Slot.tsx": $Slot,
    "./islands/_OtrioOld.tsx": $_OtrioOld,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
